config/routes.rb
Rails.application.routes.draw do
    root to: 'pages#home'
    
    # Tell the routes file that we will write a file under (controllers)/users/registrations
    # to extend the functionality of the base devise registrations controller.
    devise_for :users, controllers: { registrations: 'users/registrations' }
    resources :users do
        resource :profile
    end
    resources :contacts, only: :create
    get 'about', to: 'pages#about'
    get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_one_attached :profile_picture
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :only_current_user
  
  # GET - /users/:user_id/profile
  def show
    redirect_to user_path(params[:user_id])
  end
  
  # GET - /users/:user_id/profile/edit
  def edit
    @profile = Profile.find_by user_id: current_user.id
  end
  
  # PUT/PATCH - /users/:user_id/profile
  # (This request is also made upon pressing the submit button on the 'edit' page)
  def update
    # If profile successfully updated
    if User.find( params[:user_id] ).profile.update_attributes(profile_params)
      # Flash a success message and redirect the user to their profile view
      flash[:success] = "Profile successfully updated."
      redirect_to user_path(params[:user_id])
    else
      # Else refresh the edit view
      flash[:error] = "Error updating your profile; Please try again."
      render action: :edit
    end
  end
  
  private
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :profile_picture, :job_title, :phone_number, :email, :description)
    end
    
    def only_current_user
      redirect_to user_path(current_user.id) unless User.find(params[:user_id]).id.to_i == current_user.id
    end
end

app/views/profiles/edit.html.erb
<div class="row">
  <div class="col-md-4 mx-auto">
    <div class="card">
      <div class="card-header text-center">
        <h4 class="my-auto">Edit your profile</h4>
      </div>
      <div class="card-body">
        <%= form_for @profile, url: user_profile_path, html: { multipart: true } do |f| %>
          <div class="form-group">
            <%= f.label :first_name %>
            <%= f.text_field :first_name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :profile_picture %>
            <%= f.file_field :profile_picture, class: 'form-control-file' %>
          </div>
          <div class="form-group">
            <%= f.label :job_title %>
            <%= f.select :job_title, ['Developer', 'Entrepreneur', 'Investor'], { prompt: 'Please select an option' }, { class: 'form-control' } %>
          </div>
          <div class="form-group">
            <%= f.label :phone_number %>
            <%= f.text_field :phone_number, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.submit "Update Profile", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<!-- Redirects to GET - /users/:id ! -->