config/routes.rb
Rails.application.routes.draw do
    root to: 'pages#home'
    
    # Tell the routes file that we will write a file under (controllers)/users/registrations
    # to extend the functionality of the base devise registrations controller.
    devise_for :users, controllers: { registrations: 'users/registrations' }
    resources :users do
        resource :profile
    end
    resources :contacts, only: :create
    get 'about', to: 'pages#about'
    get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
  
  PRO_PRICE_ID = ENV["pro_price_id"] # Access price ID ENV variable
  attr_accessor :stripe_card_token # Access the stripe_card_token attribute injected into the pro_form by stripe.js
  def save_pro
    # Fields clear devise validations
    if valid?
      
=begin
This method is where the magic happens.
The 'create' method called under the Stripe gem will:
  Send the customer's details (email, plan_id, one-time Card Token) to Stripe
  Stripe will then create a new subscription for us in their DB (visible from the Stripe dashboard)
  Stripe will then return a Customer Token to us (DO NOT CONFUSE WITH CARD TOKEN)
  We will assign this Customer Token to the customer variable, and
  Save the customer's details (user, pass), along with the Customer Token to our own DB,
  We can then use the Customer Token to charge the customer recurringly for the subscription,
  Without having to worry about legal complications of saving CC info to our DB. 
=end
      
      # Create Stripe customer object
      customer = Stripe::Customer.create(
        email: email
      )
      
      # Create payment method using customer's card
      customerPaymentMethod = Stripe::PaymentMethod.create({
        type: 'card',
        card: { token: stripe_card_token }
      })
      
      # Attach payment method to customer
      Stripe::PaymentMethod.attach(
        customerPaymentMethod.id,
        { customer: customer.id }
      )
      
      # Set created payment method as customer's default payment method
      Stripe::Customer.update(
        customer.id,
        { invoice_settings: { default_payment_method: customerPaymentMethod.id } }
      )
      
      # Create the subscription
      subscription = Stripe::Subscription.create({
        customer: customer.id,
        items: [ { price: PRO_PRICE_ID } ]
      })
      
      # Save info - user, pass, stripe tokens - to database
      self.stripe_subscription_token = subscription.id
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :select_plan, only: :new
  def create
    super do |resource|
      # When the extended controller is called, if 'plans' exists in the params,
      # set the user(referred to as 'resource')'s plan_id field to the current value in params.
      if params[:plan]
        resource.plan_id = params[:plan]
        
        # If the user is signing up for a pro plan, run the special save_with_registration
        # method defined in the model, that will save the Customer Token returned by Stripe,
        # along with the user details (user,pass) that are ordinarily saved.
        if resource.plan_id == 2
          resource.save_pro # Save with Stripe fields for pro users
        else
          resource.save # Normal save for basic users
        end
      end
    end
    # Generate Profile object for new user & save it
    @profile = resource.build_profile( profile_params ).save
  end
  
  private
    def select_plan
      unless (params[:plan] == '1' || params[:plan] == '2')
        flash[:notice] = "Please select a valid plan."
        redirect_to root_url
      end
    end
    
  private
    def profile_params
      params.require(:user).permit(:email)
    end
end

    

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  # GET - /users/:id
  def show
    @user = User.find(params[:id])
  end
  
  # GET - /users
  def index
    @users = User.where.not(id: current_user.id).includes(:profile)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def job_title_icon(user)
    case user.profile.job_title
    when "Developer"
      "<i class='fas fa-code mr-2'></i>".html_safe
    when "Entrepreneur"
      "<i class='fas fa-user-tie mr-2'></i>".html_safe
    else
      "<i class='fas fa-hand-holding-usd mr-2'></i>".html_safe
    end
  end
end

app/views/users/index.html.erb
<div class="container">
  <% @users.each do |u| %>
    <div class="card index-card bg-light my-4">
      <div class="card-body">
        <div class="media position-relative">
          <%= image_tag(u.profile.profile_picture, class: 'dp align-self-center mr-4') %>
          <div class="media-body">
            <h5><b><%= u.profile.first_name %> <%= u.profile.last_name %></b></h5><hr/>
            <p>
              <%= u.profile.job_title %>
              <% if u.plan_id == 2 %>
                <span class="badge badge-success ml-1">Pro</span>
              <% end %>
            </p>
            <%= link_to "", user_path(u.id), class: 'stretched-link' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="card bg-light mb-3">
    <div class="card-body">
      <div class="media">
        <% if @user.profile.profile_picture.attached? %>
          <%= image_tag(@user.profile.profile_picture, class: 'img-fluid mr-4') %>
        <% end %>
        <div class="media-body">
          <h4><%= job_title_icon(@user) %><%= @user.profile.job_title %></h4><hr/>
          <p><strong>Name: </strong><%= @user.profile.first_name %> <%= @user.profile.last_name %></p>
          <% if current_user.plan_id == 2 %>
            <p><strong>Phone number: </strong><%= @user.profile.phone_number %></p>
            <p><strong>Email: </strong><%= @user.profile.email %></p>
          <% end %>
          <% if params[:id].to_i == current_user.id %>
            <%= link_to "Edit profile", edit_user_profile_path(current_user.id), class: 'btn btn-info mt-2' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>