config/routes.rb
Rails.application.routes.draw do
    root to: 'pages#home'
    
    # Tell the routes file that we will write a file under (controllers)/users/registrations
    # to extend the functionality of the base devise registrations controller.
    devise_for :users, controllers: { registrations: 'users/registrations' }
    resources :users do
        resource :profile
    end
    resources :contacts, only: :create
    get 'about', to: 'pages#about'
    get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/views/layouts/application.html.erb
<!-- This html page shows up on every page of our website/app. -->
<!DOCTYPE html>
<html>
    <head>
        <title>DevMatch</title>
        <%= csrf_meta_tags %>
        <link href="//fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">   <!-- Google fonts embed-->
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> <!-- Bootstrap Responsive meta tag -->
        <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
    </head>
    
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
            <div class="container">
                <!-- The Rails way to add links -->
                <%= link_to root_path, class: "navbar-brand" do %>    <!-- This way is for if you need to group multiple clickables together, for instance an icon & text, in this case. -->
                    <i class ="fas fa-users mr-2"></i>DevMatch
                <% end %>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-nav-collapse" aria-controls="main-nav-collapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="main-nav-collapse">
                    <ul class="navbar-nav ml-auto">
                        <% if user_signed_in? %>
                            <li class="nav-item"><%= link_to "Community", users_path, class: 'nav-link' %></li>
                        <% end %>
                        <li class="nav-item"><%= link_to "About", about_path, class: 'nav-link' %></li>    <!-- This way is for if you only need clickable text. -->
                        <li class="nav-item"><%= link_to "Contact Us", new_contact_path, class: 'nav-link' %></li>
                        <% if user_signed_in? %>
                            <div class="dropdown ml-2">
                                <button type="button" class="btn btn-primary btn-md dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Account
                                </button>
                                <div class="dropdown-menu">
                                    <%= link_to "Profile", user_path(current_user.id), class: 'dropdown-item' %>
                                    <%= link_to "Account", edit_user_registration_path, class: 'dropdown-item' %>
                                    <div class="dropdown-divider"></div>
                                    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
                                </div>
                            </div>
                        <% else %>
                            <li><%= link_to "Login", new_user_session_path, class: 'btn btn-primary ml-2' %></li>
                        <% end %>
                    </ul>
                </div>
            </div>    
        </nav>    
            
        <div class="container">
            <% if !flash.empty? %>
                <div class="alert alert-warning alert-dismissible" role="alert">
                    <% flash.each do |key, value| %>
                        <%= "#{value}".html_safe %>
                    <% end %>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
            <% end %>
        </div>
        <%= yield %>   <!-- This line is where Rails injects the code from the home.html.erb file. -->
    </body>
</html>